#!/system/bin/sh


size_output_raw()
{
 if busybox test -s "$r_name".raw.img; then
 size_out="$(busybox stat -c %s "$r_name".raw.img)"
 size_free="$(busybox expr "$(tune2fs -l "$r_name".raw.img | busybox awk '/Free blocks:/ { print $3 }')" \* 4096 / 1024 / 1024)"
 echo ".....Size raw == $size_out byte"
 echo ".....Free space: $size_free mb"
 echo
fi
 return
}


#r_name=$(echo $file | busybox sed 's!.*\/!!' | busybox awk -F"-|_|[+]|[.]|[{]|[(]" '{ print $1 }')

 r="$(busybox basename $file)"
 r_name=${r%.*}


 if [ -f ./"$file" ]; then
if [ ! -z "$(busybox hexdump -C -n 4 ./"$file" | grep '3a ff 26 ed')" ]; then
echo
echo ".....Conversion..."
echo
 simg2img ./"$file" ./"$r_name".raw.img
 if [ $(echo $?) -eq 0 ]; then
echo ".....Received raw image: \""$r_name".raw.img\"!"
 size_output_raw
echo
 else
 echo
 echo ".....Error while converting!"
 echo
 fi
 else
 echo
 echo ".....Image is not sparse."
 echo
 fi
 else
 echo
 echo ".....There is no "$file" image in the folder."
 echo
 fi


